import { PublicKey, TransactionInstruction } from "@solana/web3.js";
import { Market, Swapper, TokenID } from "../types";
import { Parser } from "../utils/Parser";
export declare const RAYDIUM_AMM_PROGRAM: PublicKey;
export declare class RaydiumMarket extends Market implements Swapper {
    tokenIdA: TokenID;
    tokenIdB: TokenID;
    amm: PublicKey;
    ammAuthority: PublicKey;
    openOrders: PublicKey;
    targetOrders: PublicKey;
    raydiumVaultA: PublicKey;
    raydiumVaultB: PublicKey;
    serumMarket: PublicKey;
    serumBids: PublicKey;
    serumAsks: PublicKey;
    serumEvents: PublicKey;
    serumVaultA: PublicKey;
    serumVaultB: PublicKey;
    serumVaultSigner: PublicKey;
    mintA: PublicKey;
    mintB: PublicKey;
    INST_LAYOUT: Parser;
    constructor(name: string, tokenIdA: TokenID, tokenIdB: TokenID, amm: PublicKey, ammAuthority: PublicKey, openOrders: PublicKey, targetOrders: PublicKey, raydiumVaultA: PublicKey, raydiumVaultB: PublicKey, serumMarket: PublicKey, serumBids: PublicKey, serumAsks: PublicKey, serumEvents: PublicKey, serumVaultA: PublicKey, serumVaultB: PublicKey, serumVaultSigner: PublicKey);
    getSwapper(): Swapper;
    createSwapInstructions(fromToken: TokenID, fromAmount: number, fromTokenAccount: PublicKey, toToken: TokenID, minToAmount: number, toTokenAccount: PublicKey, tradeOwner: PublicKey): Promise<TransactionInstruction[]>;
}
export declare const RAYDIUM_BTC_USDC_MARKET: RaydiumMarket;
export declare const RAYDIUM_ETH_USDC_MARKET: RaydiumMarket;
export declare const RAYDIUM_SOL_USDC_MARKET: RaydiumMarket;
